#!/bin/sh
# --- WARNING (versions and timestamps) ---
#
# Do not use timestamps for generating this package version, because it will be
# built on two different machines, and that will cause the version to differ
set -e
codename=$(python -c 'from lsb_release import get_lsb_information as g; print g()["CODENAME"]')
fullversion=$(git describe --tags --match '[0-9].[0-9]*')
git checkout debian/changelog
debchange -m -D unstable --force-distribution -v "$fullversion~$codename" "Automatic build"
debuild -us -uc -b

